### PR TITLE
0.25 upgrade

### LINKED ISSUE #88: Upgrade to version 0.25
Partner is happy for us to upgrade. 

They will find someone to translate missing strings:

Kinyarwanda (128 strings need to be translated): https://www.transifex.com/mysociety/alaveteli/viewstrings/#rw/apppot/92362970?translated=no

French (119 strings need to be translated): https://www.transifex.com/mysociety/alaveteli/viewstrings/#fr/apppot/92362970?translated=no

### PR DESCRIPTION
**Pull request by lizconlan**
First pass attempt - some colour/styling changes could use a second look. Screenshots of the main visual changes included in the comments below along with some notes about missing translations and a question about whether old text should be kept.

Template files which turned out to be identical to current core once the whitespace and line wrapping issues had been addressed have been deleted leaving a much simpler theme.

Connects to #88

### CODE REVIEW

**Comment by lizconlan** [comment]
# Notable visual changes

## Front page

The front page of the site has changed quite a bit since version 0.22.4.9 and currently looks something like this:

screen shot 2016-08-19 at 15 26 34

(I'm not entirely convinced by my colour choices, I was more focused on getting the layout right.)

**Note** the slight change in the colour of the search box text is deliberate to provide more contrast, the repositioning of "Sign in or sign up" is accidental but I quite liked it so left it in for feedback (more than happy to move it back to where it was on the old design).


## New request page wording

The wording in the request advice sidebar has also changed...

Current site wording:

screen shot 2016-08-19 at 14 18 51

Updated wording:

screen shot 2016-08-19 at 14 20 14

In particular the phrase "There may be risks associated with using your real name. Read our advice about using a pseudonym" is no longer used - it can be kept if required but will mean more work for future translators (and maintaining a theme-specific Transifex project in addition to the translations in the main Alaveteli project).

**Comment by lizconlan** [comment]
I've retained the old sidebar wording about using a pseudonym for now, but that's the only difference between the core `/view/request/new.html.erb` template and theme version so the theme file can be deleted if the old text is not required.

**Comment by lizconlan** [comment]
The rake task that checks the help pages found some missing sections in the translated versions:

```
theme: sobanukirwa-theme locale: en

No missing templates or sections

theme: sobanukirwa-theme locale: rw

Missing section: postal_answer in template privacy
Missing help template:  _why_they_should_reply_by_email rw

theme: sobanukirwa-theme locale: fr

Missing section: full_address in template privacy
Missing section: postal_answer in template privacy
Missing help template:  _why_they_should_reply_by_email fr
```

**Comment by lizconlan** [comment]
Also of possible note - have imported `block-grid` from Foundation as the simplest way of retaining the original footer layout. Someone with better CSS/Foundation skillz may know of a better way.

**Comment by garethrees** [comment]
Quick first pass:

> currently looks something like this

- Screenshot on the whole looks good
- Looks like its missing the thin green, yellow and blue banner at the top
- Should use the new style locale switcher

> I'm not entirely convinced by my colour choices

- Should keep the existing colours as much as possible. The green looks different to me.
- I'd probably make the button in the black box green.

> change in the colour of the search box text is deliberate to provide more contrast

+1, much better.

> repositioning of "Sign in or sign up"

Should be in the same position as alavetelitheme (i.e. no customisation applied to `sobanukirwa-theme`.

> "There may be risks associated with using your real name. Read our advice about using a pseudonym"

This should be kept

> The rake task that checks the help pages found some missing sections in the translated versions

Out of scope for this issue/PR

**Comment by lizconlan** [comment]
> * Looks like its missing the thin green, yellow and blue banner at the top

I think that was just my clumsy cropping of the screenshot

**Comment by garethrees** [comment]
FWIW I like [Paparazzi!](https://derailer.org/paparazzi/) for full page screenshots.

**Comment by lizconlan** [comment]
rwanda-screenshot

**Comment by lizconlan** [comment]
With colours and the banner section fixed:

rwanda-screenshot

**Comment by lizconlan** [comment]
Locale switcher detail (when clicked):

screen shot 2016-08-30 at 16 41 03

Have nudged the locale switcher down a bit so that it appears to be vertically aligned to the logo text as it looked a bit odd otherwise.

**Comment by garethrees** [comment]
> With colours and the banner section fixed:

That green doesn't look right. https://github.com/mysociety/sobanukirwa-theme/blob/master/assets/stylesheets/responsive/custom.scss#L7

**Comment by lizconlan** [comment]
latest screenshots:

Homepage:

rwanda-screenshot

Request page:

(I've darkened the yellow slightly for the text but there still might not be enough contrast against the grey)

rwanda-request

Mobile homepage:

rwanda-mobile

rwanda-mobile-menu-open

**Comment by garethrees** [comment]
> I've darkened the yellow slightly…

Looks like you've got `develop` checked out, but we're only upgrading to `0.25.0.x`.

There's a big diff in `app/views/request/new.html.erb`.

I'd apply this to the homepage to tighten up the colour scheme:

```diff
diff --git a/assets/stylesheets/responsive/custom.scss b/assets/stylesheets/responsive/custom.scss
index 7df7423..ae7e279 100644
--- a/assets/stylesheets/responsive/custom.scss
+++ b/assets/stylesheets/responsive/custom.scss
@@ -784,7 +784,7 @@ dt {
 .steps__step-number {
   height: 3.5em;
   width: 3.5em;
-  background-color: $color_green;
+  background-color: $color_sobanukirwa_green;
   box-shadow: 0 1px 2px transparentize($color_black, 0.75);
   padding: 1em;
   border-radius: 100%;
@@ -853,12 +853,12 @@ dt {
 .homepage-hero {
   .new-request__make-new-requests {
     @include button-base;
-    background-color: desaturate(darken($color_sobanukirwa_green, 10%), 5%);
+    background-color: desaturate($color_sobanukirwa_green, 5%);
     color: $color_white;
     &:hover,
     &:active,
     &:focus {
-      background-color: darken($color_sobanukirwa_green, 20%);
+      background-color: darken($color_sobanukirwa_green, 10%);
     }
   }
 }
```

**Comment by lizconlan** [comment]
## Homepage
rwanda-screenshot

## Request page
rwanda-request

## Mobile
rwanda-mobile

**Comment by garethrees** [comment]
Looks good. Squash it down but we'll have to wait 'til translations are done before merge.

Also need to generate the theme translations, but will do that after merge.

**Pull request closed without merging**
